### ISSUE TITLE
Restore v3 env variable handling?

### ISSUE THREAD

**Issue by arlampin** [JetBrains/js-graphql-intellij-plugin#663]
**Describe the bug**
We have following config in our project:

```
schema: "graphql-schema/schema.graphql"
extensions:
  endpoints:
    dev:
      url: "http://localhost:9000/graphql"
      headers:
        authorization: "Bearer ${GQL_DEV_TOKEN}"
    staging:
      url: "https://api-staging.REDACTED/graphql"
      headers:
        authorization: "Bearer ${GQL_STAGING_TOKEN}"
    production:
      url: "https://api.REDACTED/graphql"
      headers:
        authorization: "Bearer ${GQL_PRODUCTION_TOKEN}"
```

Each developer has GQL_DEV_TOKEN in their local `.env.local` file, but staging/production tokens are only created and configured as needed.

In v3 doing a request against dev endpoint didn't ask GQL_STAGING_TOKEN or GQL_PRODUCTION_TOKEN keys, so they almost never needed to be configured. But with v4, doing any request asks for both missing tokens. It would be very convenient if v3's env variable handling could be restored.

**Version and Environment Details**
IDE name and version: IntelliJ IDEA 2023.1 (Ultimate Edition)
Plugin version: 4.0.0
