### ISSUE TITLE
Error on IntelliJ when "Run Introspection Query" and using wildcards on the schema config

### ISSUE THREAD

**Issue by ciandt-crodrigues** [JetBrains/js-graphql-intellij-plugin#675]
# Bug
IntelliJ popup the error Invalid "GraphQL configuration file" when clicking on the Run Introspection Query (the refresh icon on the side of the play)

# Environment
Windows, IntelliJ IDEA 2023.1.2 (Community Edition)
Folder Structure:
```
Backend/
    graphql.config.yml
        microservices
        |   microservice1
        |   |   graphql
        |   |   |   microservice1.schema.graphqls
        |   |   graphql-documents
        |   |   |   <docs>.graphql
        |   microservice2
        |   |   graphql
        |   |   |   microservice2.schema.graphqls
        |   |   graphql-documents:
        |   |   |   <docs>.graphql
        bffs
        |   web-bff
        |   |   graphql
        |   |   |   microservice1.schema.graphqls
        |   |   graphql-documents
        |   |   |   <docs>.graphql
```       

Config file
```
projects:
  microservice1:
    schema: 'microservices/microservice1/**/*.schema.graphqls'
    documents: '**/graphql-documents/microservice1/*.graphql'
    extensions:
        endpoints:
            orders: <MyDevEnv>
  microservice2:
    schema: 'microservices/microservice2/**/*.schema.graphqls'
    documents: '**/graphql-documents/microservice2/*.graphql'
    extensions:
        endpoints:
            orders: <MyDevEnv>
  bffs:
    schema: 'bffs/web-bff/**/*.schema.graphqls'
```
So, My microservices can communicate with each other, and the BFF communicates with both.
The config is fine, it works, I have lint on the proper documents matching the correct service they call, and I can test the query and mutations in development against my dev server.

The annoying problem is that I get a popup on the IDE when I run the refresh saying 
```
Please provide a valid path to schema in the config file. The first schema pattern should contain the correct path to a file in the file system. Provided: 'microservices/microservice1/**/*.schema.graphqls'.
```
If I go there on the config file and replace the schema for the complete path (without wildcards) on the schema it works just fine.

**Comment by lorthirk** [comment]
It seems that glob pattern is simply not working. This `.graphql.config.yml` returns the same error when introspecting:

```
schema: './adapter/web/**/*.graphqls'
extensions:
  endpoints:
    local:
      url: http://localhost:8910/graphql
      headers:
        Authorization: Bearer ${TOKEN}
```

all my `.graphqls` files are under `adapter/web/src/main/resources/schemas/`.
