### ISSUE TITLE
@octokit/graphql-schema not working

### ISSUE THREAD

**Issue by antonmedv** [JetBrains/js-graphql-intellij-plugin#692]
**Describe the bug**
For some reason schema not working, but if I put same file in project files - it works.

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
Install `npm i @octokit/graphql-schema`

Setup with:

```yaml
schema: node_modules/@octokit/graphql-schema/schema.graphql
extensions:
  endpoints:
    GitHub:
      url: https://api.github.com/graphql
      headers:
        Authorization: bearer ${GITHUB_TOKEN}


```

**Expected behavior**
Schema works

**Screenshots**

<img width="383" alt="Screenshot 2023-10-03 at 15 01 54" src="https://github.com/JetBrains/js-graphql-intellij-plugin/assets/141232/c23327ff-2f09-419f-bc45-44c5035432f9">

**Version and Environment Details**

Operation system: macOs
IDE name and version: latest (Just updated)
Plugin version: latest (Just updated)

**Additional context**
