### ISSUE TITLE
Auto-complete issue with multiple projects and schemas

### ISSUE THREAD

**Issue by benjamindulau** [JetBrains/js-graphql-intellij-plugin#714]
**Describe the bug**

We're trying to setup multiple schemas in a project but auto-complete in code injections seems to only supports one of the defined project schemas.

One schema is our internal schema.
The other one is a dumped schema from Strapi and is the reason why we need to add multi-schema support in the project.

Before we had this configuration:
```yaml
schema:
    - 'src/ST/GraphQL/schema/**/*.graphql'
```

Only one schema, so far so good..

Now we're trying to work with this configuration
```yaml
# .graphqlrl.yml
projects:
    # our own schema
    catalog:
        schema:
            - 'src/ST/GraphQL/schema/**/*.graphql'
    # the Strapi schema that we dumped
    cms:
        schema:
            - 'assets/website/remix/app/types/cms.graphql'
```

Problem is we get autocomplete for the first schema (catalog) but not the other one, here is a video showing this:
https://github.com/JetBrains/js-graphql-intellij-plugin/assets/430689/aad02209-2b39-4187-b9ba-daa4f838ee59

And as you can see in the following screenshots, both schemas are recognized by the plugin, and the `guides` field exists in the dumped `cms.graphql` schema file used by the plugin:
![Capture d’écran 2024-05-20 à 12 16 15](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/430689/62af8c22-1961-4217-811e-d6d60e26a149)
![Capture d’écran 2024-05-20 à 12 18 24](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/430689/be7a740e-eda4-40fb-b0e3-1574b7e7f077)

**Version and Environment Details**
Operation system: macOS Ventura 13.2.1
IDE name and version:
![Capture d’écran 2024-05-20 à 12 21 23](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/430689/d305ac2a-b394-4389-aee5-634ef9aa90ae)
Plugin version: 241.14494.150
