### ISSUE TITLE
How to use more than one remote schema with full error checking?

### ISSUE THREAD

**Issue by cwilso03** [JetBrains/js-graphql-intellij-plugin#728]
I'm working on a project that interfaces with Shopify's GraphQL APIs.  For those unaware, Shopify has an "Admin" API, accessible via one URL, and a "Storefront" API accessible from a slightly different URL.  Each of these APIs has a different schema.

I have configured my `graphql.config.yml` file to reference each of these endpoints and schemas:

```yaml
schema:
  - https://mystore.myshopify.com/admin/api/2024-10/graphql.json:
      headers:
        X-Shopify-Access-Token: ${SHOPIFY_ADMIN_API_ACCESS_TOKEN}
  - https://mystore.myshopify.com/api/2024-10/graphql.json:
      headers:
        Shopify-Storefront-Private-Token: ${SHOPIFY_STOREFRONT_API_ACCESS_TOKEN}
```

I can successfully run introspection queries on each of the schemas. 

The problem is that I frequently need to access data from both of the APIs (via separate queries, of course).  While this works from a transpiled code standpoint, I see errors in my editor window for the queries of whichever schema I haven't run the introspection on.  So, if I run introspection on the Admin API schema, the Storefront queries show errors.  And vice-versa if I run the introspection on the Storefront schema.

Is there a way to successfully use both schemas with full error checking, perhaps with an injection along with the `#graphql` I already put at the top of my query?
