### ISSUE TITLE
Autocompletion stopped working since upgrading webstrom to 2024.3 

### ISSUE THREAD

**Issue by ItaiYosephi** [JetBrains/js-graphql-intellij-plugin#729]
**Describe the bug**
Since upgrading Webstorm, there's no autocompletion, no red underline when trying to query for non existing fields, and so on.

**Expected behavior**
Schema should be detected properly, autocompletion should work, 

**Screenshots**

Screenshot taken in  Webstorm version 2024.2.4, and plugin version 242.21829.3.
Autocomplete  is working, and `securityScanSources` has line through indicating it's deprecated

![CleanShot 2024-11-18 at 13 02 11](https://github.com/user-attachments/assets/28fc6f65-48dc-49f7-b3aa-60cb0e20ca78)

Screenshot taken in Webstorm version 2024.3, and plugin version 243.21565.122:
Only `__typename` is autocompleted, and no line through

![CleanShot 2024-11-18 at 13 04 24](https://github.com/user-attachments/assets/e46cf85e-7372-40a1-948a-6536fbe7d959)

**Version and Environment Details**
Operation system: MacOS
IDE name and version: Webstorm 2024.3
Plugin version: 243.21565.122

**Comment by vepanimas** [comment]
@ItaiYosephi Hi! Could you please open a GraphQL tool window and share the errors you see there?

**Comment by ItaiYosephi** [comment]
@vepanimas 
Hi, thanks for you response.
I guess we've reached the limit?
![CleanShot 2024-11-25 at 09 51 23](https://github.com/user-attachments/assets/354153fe-1877-43d7-a899-6788ec5bdd01)

**Comment by ItaiYosephi** [comment]
@vepanimas hi, any update on that?

**Comment by vepanimas** [comment]
Hi @ItaiYosephi! Could you please run `grep -rE '^(schema|type|input|scalar|directive|enum|extend)' --include='*.graphql' . | wc -` in your repo and share the number? 

We're working on optimizing schema building for some unusual projects containing thousands of non-executable schemas, e.g. for testing purposes. These schemas aren't meant to be used but still significantly degrade performance, so we introduced this heuristic to address the issue. So far, your report is the only one after the latest release, so you probably have an unusually huge schema. Could you share some details about the project? Is it some open API which I can test too?

**Comment by vepanimas** [comment]
And one more question - are all the types in the same single file? If so, maybe we shouldn't count that case as an overflow.

**Comment by ItaiYosephi** [comment]
Hi @vepanimas ,
The number is `4920`.
Our project is big, and our schema grows bigger all the time. it's not open, so you can't test it.
The types are all in one file (we use codegen to generate it from the backend package).

**Comment by JG9A** [comment]
Hi 

Hope it is OK I am jumping in here - I am trying to work with Atlassian graphql to fetch Jira only relevant part of the schema and I set this:
```
schema:
  - gen/schema.graphql:
     
extensions:
  endpoints:
    jira:
      url: https://pdc-amat-prod.atlassian.net/gateway/api/graphql
      headers:
        Authorization: Basic ${JIRA_API_TOKEN}
        X-ExperimentalApi: JiraIssueSearch
      introspect: true
```

I am getting the limit error and I ran 
`grep -rE '^(schema|type|input|scalar|directive|enum|extend)' --include='*.graphql' . | wc -l`

I am getting 10859 - is there a way to filter the fetched schema somehow to relevant part only? 

I tried this:
```
schema:
  - gen/schema.graphql:
      include:
        - "Issue*"
        - "Jira*"
        - "Project*"
        - "User*"
        - "Team*"
        - "Board*"
        - "Sprint*"
        - "WorkLog*"
        - "Comment*"
        - "Task*"
        - "Priority*"
        - "Status*"
      exclude:
        - "*Confluence*"
        - "*Bitbucket*"
        - "*Page*"
        - "*Blog*"
        - "*Content*"
        - "*Space*"
        - "*Notification*"
        - "*WebPanel*"
        - "*WebItem*"
```

but the result is the same 

Thanks

**Comment by vepanimas** [comment]
@JG9A oh, that's a huge schema, I'll look at how it performs. For now, you can change a registry key to increase the predefined limit `graphql.schema.size.definitions.limit`:

![Image](https://github.com/user-attachments/assets/4e96d893-9c6f-43fe-a1c0-ed7aa90582dc)

Also, I noticed that you have an extra colon at the end of the schema path, looks like a typo:

```
schema:
  - gen/schema.graphql:     # <-- a colon here it not needed
     
extensions:
  endpoints:
    jira:
      url: https://pdc-amat-prod.atlassian.net/gateway/api/graphql
      headers:
        Authorization: Basic ${JIRA_API_TOKEN}
        X-ExperimentalApi: JiraIssueSearch
      introspect: true
```
