### ISSUE TITLE
Webstorm update 2024.3 broke schema discovery in excluded files

### ISSUE THREAD

**Issue by reckter** [JetBrains/js-graphql-intellij-plugin#730]
**Describe the bug**
After updating to 2024.3, graphql didn't correctly pick up the api schema, resulting in no types found, and lots of errors.

Setup:
We have a monorepository with one schema package that "compiles" a bunch of graphql files into one `api.graphql` file.
located in `/packages/schema/build/graphql/api.graphql`

In our `graphql.config.yml`, we mention this file directly:
```yml
schema: packages/schema/build/graphql/api.graphql
projects:
  frontend:
    documents: "apps/frontend/**/*.{graphql,js,ts,jsx,tsx}"
```
This worked without problems in earlier webstorm versions.
If I move our `api.graphql` file outside of the `build` directory it still works as it did before.
The `build` directory is on the `.gitignore` and is marked to ignore in the IDE

Operation system: macOS 15.1
IDE name and version: Webstorm 2024.3
Plugin version: 243.21565.122

**Additional context**
