### ISSUE TITLE
GraphQL plugin is not loading environment variables from .env file

### ISSUE THREAD

**Issue by arkandias** [JetBrains/js-graphql-intellij-plugin#733]
I'm using GraphQL plugin (243.22562.13) in WebStorm 2024.3.1.1.

Here is my `graphql.config.yml` file (in project root):

```yaml
schema: schema.graphql
extensions:
  endpoints:
    dev:
      url: ${ENDPOINT}
documents: "**/*.graphql"
```

And here is my `.env` file (in project root):

```
ENDPOINT=http://localhost:8090/v1/graphql
```

Yet the plugin does not replace `${ENDPOINT}` with its value from `.env`.
I can edit it in the "GraphQL Environment Variables" dialog that I can open by clicking on the "Edit Environment Variables" button in the plugin toolbar, but it should be loaded automatically from the `.env` file (according to the doc).
