### ISSUE TITLE
Failed to evaluate config (.graphqlrc.js file)

### ISSUE THREAD

**Issue by mira-paulik-pb** [JetBrains/js-graphql-intellij-plugin#744]
**Description**
Webstorm is not picking up `graphqlrc.js` file configuration and it shows me many Schema Errors on GraphQL plugin tab (view). The same configuration in YAML format works like a charm. The [plugin website](https://www.jetbrains.com/help/webstorm/graphql.html#graphql_configuration_files) shows that this file should be supported and its syntax seems to be valid.

`.graphqlrc.js` configuration file 
```javascript
module.exports = {
  schema: [
    'libs/graphql/schema/extensions/polling.graphql',
    'libs/graphql/schema/schema.graphql',
    'libs/graphql/schema/relay-directives.graphql',
  ],
  documents: ['libs/**/*.{ts,tsx}', '!libs/tools/**/*'],
};
```

`.graphqlrc.yml` configuration file 
```yaml
schema:
  - libs/graphql/schema/extensions/polling.graphql
  - libs/graphql/schema/schema.graphql
  - libs/graphql/schema/relay-directives.graphql

documents:
  - libs/**/*.{ts,tsx}
  - '!libs/tools/**/*'
```

**Version and Environment Details**
WebStorm 2025.1
Build #WS-251.23774.424, built on April 14, 2025
Runtime version: 21.0.6+9-b895.109 aarch64 (JCEF 122.1.9)
macOS 15.0.1
Non-Bundled Plugins:
  com.intellij.lang.jsgraphql (251.23774.318)
